///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String latoLatoBlack = 'assets/fonts/Lato/Lato-Black.ttf';
  static const String latoLatoBlackItalic =
      'assets/fonts/Lato/Lato-BlackItalic.ttf';
  static const String latoLatoBold = 'assets/fonts/Lato/Lato-Bold.ttf';
  static const String latoLatoBoldItalic =
      'assets/fonts/Lato/Lato-BoldItalic.ttf';
  static const String latoLatoItalic = 'assets/fonts/Lato/Lato-Italic.ttf';
  static const String latoLatoLight = 'assets/fonts/Lato/Lato-Light.ttf';
  static const String latoLatoLightItalic =
      'assets/fonts/Lato/Lato-LightItalic.ttf';
  static const String latoLatoRegular = 'assets/fonts/Lato/Lato-Regular.ttf';
  static const String latoLatoThin = 'assets/fonts/Lato/Lato-Thin.ttf';
  static const String latoLatoThinItalic =
      'assets/fonts/Lato/Lato-ThinItalic.ttf';
  static const String latoOFL = 'assets/fonts/Lato/OFL.txt';
  static const String mobileActivecheckbox =
      'assets/images/mobile/mobile/activecheckbox.png';
  static const String mobileActivitiesimage =
      'assets/images/mobile/mobile/activitiesimage.png';
  static const String mobileAdvertbackground =
      'assets/images/mobile/mobile/advertbackground.png';
  static const String mobileAdvertcup =
      'assets/images/mobile/mobile/advertcup.png';
  static const String mobileAnxious = 'assets/images/mobile/mobile/Anxious.png';
  static const String mobileAppicon = 'assets/images/mobile/mobile/appicon.png';
  static const String mobileArrobigright =
      'assets/images/mobile/mobile/arrow big right.png';
  static const String mobileArrowlongleft =
      'assets/images/mobile/mobile/arrow long left.png';
  static const String mobileAudio = 'assets/images/mobile/mobile/audio.png';
  static const String mobileBackgroudfloatingelements =
      'assets/images/mobile/mobile/backgroud floating elements.png';
  static const String mobileBackgroudfloatingelements1 =
      'assets/images/mobile/mobile/backgroudfloatingelements1.png';
  static const String mobileBadhabit =
      'assets/images/mobile/mobile/bad habit.png';
  static const String mobileBed = 'assets/images/mobile/mobile/bed.png';
  static const String mobileBell = 'assets/images/mobile/mobile/Bell.png';
  static const String mobileBlog = 'assets/images/mobile/mobile/blog.png';
  static const String mobileBlogpostimage =
      'assets/images/mobile/mobile/blogpostimage.png';
  static const String mobileBlogpostimagea =
      'assets/images/mobile/mobile/blogpostimagea.png';
  static const String mobileBlogpostimageb =
      'assets/images/mobile/mobile/blogpostimageb.png';
  static const String mobileCalendar =
      'assets/images/mobile/mobile/calendar.png';
  static const String mobileCalm = 'assets/images/mobile/mobile/calm.png';
  static const String mobileCalmcopy =
      'assets/images/mobile/mobile/Calm copy.png';
  static const String mobileChathead =
      'assets/images/mobile/mobile/chat head.png';
  static const String mobileCheck = 'assets/images/mobile/mobile/check.png';
  static const String mobileCommunity =
      'assets/images/mobile/mobile/community.png';
  static const String mobileContactus =
      'assets/images/mobile/mobile/contactus.png';
  static const String mobileDraghandle =
      'assets/images/mobile/mobile/Drag handle.png';
  static const String mobileDumbbell =
      'assets/images/mobile/mobile/dumbbell.png';
  static const String mobileEdit = 'assets/images/mobile/mobile/edit.png';
  static const String mobileEditIcon =
      'assets/images/mobile/mobile/Edit Icon.png';
  static const String mobileEmail = 'assets/images/mobile/mobile/email.png';
  static const String mobileEmojides =
      'assets/images/mobile/mobile/emoji des.png';
  static const String mobileEnergized =
      'assets/images/mobile/mobile/Energized.png';
  static const String mobileExplorecommunity =
      'assets/images/mobile/mobile/explorecommunity.png';
  static const String mobileExploreme =
      'assets/images/mobile/mobile/exploreme.png';
  static const String mobileExploreresourses =
      'assets/images/mobile/mobile/exploreresourses.png';
  static const String mobileFacebook1 =
      'assets/images/mobile/mobile/facebook 1.png';
  static const String mobileFatigued =
      'assets/images/mobile/mobile/Fatigued.png';
  static const String mobileFavourite =
      'assets/images/mobile/mobile/favourite.png';
  static const String mobileGood = 'assets/images/mobile/mobile/Good.png';
  static const String
      mobileGoogleLogoPngSuiteEverythingYouNeedKnowAboutGoogleNewest02 =
      'assets/images/mobile/mobile/google-logo-png-suite-everything-you-need-know-about-google-newest-0 2.png';
  static const String mobileHappy = 'assets/images/mobile/mobile/Happy.png';
  static const String mobileHome = 'assets/images/mobile/mobile/home.png';
  static const String mobileHomebookmark =
      'assets/images/mobile/mobile/homebookmark.png';
  static const String mobileHomenotification =
      'assets/images/mobile/mobile/homenotification.png';
  static const String mobileIcon = 'assets/images/mobile/mobile/Icon.png';
  static const String mobileInactivecheckbox =
      'assets/images/mobile/mobile/inactivecheckbox.png';
  static const String mobileJournal = 'assets/images/mobile/mobile/journal.png';
  static const String mobileJourney = 'assets/images/mobile/mobile/Journey.png';
  static const String mobileJourneycheckedbox =
      'assets/images/mobile/mobile/journeycheckedbox.png';
  static const String mobileJourneyuncheckedbox =
      'assets/images/mobile/mobile/journeyuncheckedbox.png';
  static const String mobileLearningcenter =
      'assets/images/mobile/mobile/learning center.png';
  static const String mobileLearningcentercard =
      'assets/images/mobile/mobile/learning center card.png';
  static const String mobileLifesaversAvatar =
      'assets/images/mobile/mobile/Lifesavers Avatar.png';
  static const String mobileListcontent =
      'assets/images/mobile/mobile/list content.png';
  static const String mobileLocked = 'assets/images/mobile/mobile/locked.png';
  static const String mobileLogo = 'assets/images/mobile/mobile/Logo.png';
  static const String mobileMe = 'assets/images/mobile/mobile/me.png';
  static const String mobileMilestonecheckedbox =
      'assets/images/mobile/mobile/milestonecheckedbox.png';
  static const String mobileMilestoneuncheckedbox =
      'assets/images/mobile/mobile/milestoneuncheckedbox.png';
  static const String mobileNeutral = 'assets/images/mobile/mobile/Neutral.png';
  static const String mobileNodata = 'assets/images/mobile/mobile/no data.png';
  static const String mobileNormal = 'assets/images/mobile/mobile/Normal.png';
  static const String mobileNotificationchecked =
      'assets/images/mobile/mobile/notificationchecked.png';
  static const String mobileNotificationgoalcheck =
      'assets/images/mobile/mobile/notificationgoalcheck.png';
  static const String mobileNotificationreportcheck =
      'assets/images/mobile/mobile/notificationreportcheck.png';
  static const String mobileNotificationtaskcheck =
      'assets/images/mobile/mobile/notificationtaskcheck.png';
  static const String mobileNotificationunchecked =
      'assets/images/mobile/mobile/notificationunchecked.png';
  static const String mobileOnboardingillustration2 =
      'assets/images/mobile/mobile/Onboarding illustration 2.png';
  static const String mobilePassword =
      'assets/images/mobile/mobile/password.png';
  static const String mobilePerson = 'assets/images/mobile/mobile/Person.png';
  static const String mobilePersonaldah =
      'assets/images/mobile/mobile/personal dah.png';
  static const String mobilePhonenumber =
      'assets/images/mobile/mobile/phone number.png';
  static const String mobilePills = 'assets/images/mobile/mobile/pills.png';
  static const String mobilePlay = 'assets/images/mobile/mobile/play.png';
  static const String mobilePoor = 'assets/images/mobile/mobile/Poor.png';
  static const String mobileRead = 'assets/images/mobile/mobile/read.png';
  static const String mobileRecommended =
      'assets/images/mobile/mobile/recommended.png';
  static const String mobileResources =
      'assets/images/mobile/mobile/resources.png';
  static const String mobileSad = 'assets/images/mobile/mobile/Sad.png';
  static const String mobileSecurity =
      'assets/images/mobile/mobile/Security.png';
  static const String mobileSelfassesment =
      'assets/images/mobile/mobile/self assesment.png';
  static const String mobileSelficon =
      'assets/images/mobile/mobile/self icon.png';
  static const String mobileSeparator =
      'assets/images/mobile/mobile/Separator.png';
  static const String mobileSettings =
      'assets/images/mobile/mobile/settings.png';
  static const String mobileStrategbed =
      'assets/images/mobile/mobile/strategbed.png';
  static const String mobileStrategiesGratitude =
      'assets/images/mobile/mobile/strategiesGratitude.png';
  static const String mobileStrategiesbadhabit =
      'assets/images/mobile/mobile/strategiesbad habit.png';
  static const String mobileStrategiesbed =
      'assets/images/mobile/mobile/strategiesbed.png';
  static const String mobileStrategiesdumbbell =
      'assets/images/mobile/mobile/strategiesdumbbell.png';
  static const String mobileStrategiesdumbbell1 =
      'assets/images/mobile/mobile/strategiesdumbbell (1).png';
  static const String mobileSubtract =
      'assets/images/mobile/mobile/Subtract.png';
  static const String mobileTherapist =
      'assets/images/mobile/mobile/therapist.png';
  static const String mobileTherapistconnect =
      'assets/images/mobile/mobile/therapistconnect.png';
  static const String mobileTherapistconnectimage =
      'assets/images/mobile/mobile/therapistconnectimage.png';
  static const String mobileUsername =
      'assets/images/mobile/mobile/username.png';
  static const String mobileVeryEnergized =
      'assets/images/mobile/mobile/Very Energized.png';
  static const String mobileVeryanxious =
      'assets/images/mobile/mobile/Very anxious.png';
  static const String mobileVerycalm =
      'assets/images/mobile/mobile/Very calm.png';
  static const String mobileVeryfatigued =
      'assets/images/mobile/mobile/Very fatigued.png';
  static const String mobileVerygood =
      'assets/images/mobile/mobile/Very good.png';
  static const String mobileVeryhappy =
      'assets/images/mobile/mobile/Very happy.png';
  static const String mobileVerypoor =
      'assets/images/mobile/mobile/Very poor.png';
  static const String mobileVerysad =
      'assets/images/mobile/mobile/Very sad.png';
  static const String mobileYoga = 'assets/images/mobile/mobile/yoga.png';
  static const String mobileYourjourney =
      'assets/images/mobile/mobile/yourjourney.png';
}
